[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
candid.workspace = true
# Required otherwise the build will fail because it not find Deserialize derive inside the candid crate
serde.workspace = true
ic-cdk.workspace = true